//
//  OrderDetailInteractor.swift
//  Playfull_test
//
//  Created by ISOL on 11/09/18.
//  Copyright (c) 2018 Example. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrderDetailBusinessLogic
{
  func getOrderDetails(request: OrderDetail.GetOrderDetails.Request)
}

protocol OrderDetailDataStore
{
  var orderFullData: Order? { get set }
}

class OrderDetailInteractor: OrderDetailBusinessLogic, OrderDetailDataStore
{
  var presenter: OrderDetailPresentationLogic?
  var worker: OrderDetailWorker?
  var orderFullData: Order?
    
    
  // MARK: Get Order Details
    
  func getOrderDetails(request: OrderDetail.GetOrderDetails.Request)
  {
//    worker = OrderDetailWorker()
//    worker?.doSomeWork()
    
    if(orderFullData != nil){
        let response = OrderDetail.GetOrderDetails.Response(order: orderFullData)
        presenter?.presentOrderDetails(response: response)
    } else {
        presenter?.failedToGetOrderDetails(message: "Order detail data not available")
    }
  }
}
