//
//  OrderDetailModels.swift
//  Playfull_test
//
//  Created by ISOL on 11/09/18.
//  Copyright (c) 2018 Example. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OrderDetail
{
  // MARK: Use cases
  
  enum GetOrderDetails
  {
    struct Request
    {
    }
    struct Response
    {
        var order: Order?
    }
    struct ViewModel
    {
        var restaurantName: String?
        var restaurantLogo: String?
        var orderDate: String?
        var status: String?
        var total: String?
        var openStatus: String?
        var taxAmount: String?
        var items: [ItemDetail]?
        var orderUUID: String
        struct ItemDetail
        {
            var name: String?
            var selectedOptionsDescription: String?
            var quantity: String?
            var priceAmount: String?
        }
        
    }
  }
}
