//
//  OrderHistoryModels.swift
//  Playfull_test
//
//  Created by ISOL on 10/09/18.
//  Copyright (c) 2018 Example. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OrderHistory
{
  // MARK: Use cases
  
  enum FetchOrders
  {
    struct Request
    {
    }
    struct Response
    {
        var orders: [Order]?
    }
    struct ViewModel
    {
        
        struct OrderDisplayData
        {
            var restaurantName: String?
            var restaurantLogo: String?
            var orderDate: String?
            var status: String?
            var total: String?
            var openStatus: String?
        }
        
        var ordersDataAry: [OrderDisplayData]
        
    }
  }
}
